#+TITLE: Personal offsec-oriented tools and scripts
#+OPTIONS: toc:nil num:nil

#+begin_example
NO WARRANTY. NO LIABILITY. LOTS OF LOVE <3
#+end_example

This repository contains some scripts and tools that I like to have at hand for
offensive security tasks. Please note that it is a constant work in progress and
is not production-ready in any way, use it at your own risks!

Some of them are stolen^Wborrowed from others. Make sure to check the original
amazing sources first and give appropriate credit to their authors :)

* Usage

#+begin_src shell
git clone --recurse-submodules https://github.com/fuzztheplanet/skw-tools ~/tools/skw
. ~/tools/skw/aliases.sh
#+end_src

If you cloned without =--recurse-submodules=, pull the submodules afterwards
with =git submodule update --init --recursive=.

* Fetching the external tools

The third-party tools under =misc/=, =net/= and =privesc/= are *not* committed
to this repository. They can be pulled by =./fetch-external-tools.sh= which
grabs a pre-compiled binary where one exists and otherwise the raw script or a
stripped source clone.

#+begin_src shell
./fetch-external-tools.sh              # fetch everything
./fetch-external-tools.sh chisel les   # fetch only the named tools
./fetch-external-tools.sh --list       # list the available tool names
./fetch-external-tools.sh --force all  # re-fetch even if already present
#+end_src

* Content

The =dockers/=, =misc/mygf/= and =misc/wordlists/= directories are tracked as
git submodules (see the =Usage= section on how to pull them).

** dockers/

- [[https://github.com/fuzztheplanet/dockers][dockers]]

** misc/

- [[https://github.com/cym13/1337dict][1337dict]]
- [[https://github.com/fuzztheplanet/mygf][mygf]]
- [[https://learn.microsoft.com/sysinternals/][sysinternals]]
- [[https://github.com/fuzztheplanet/wordlists][wordlists]]

** net/

- [[https://github.com/jpillora/chisel][chisel]]
- [[file:net/lazymap/README.org][lazymap]]
- [[https://github.com/nicocha30/ligolo-ng][ligolo-ng]]
- [[https://github.com/diegocr/netcat][netcat]], [[https://github.com/H74N/netcat-binaries][netcat-binaries]]
- [[https://github.com/besimorhino/powercat][powercat]]
- [[https://github.com/lilydjwg/socat][socat]]
- [[https://github.com/andrew-d/static-binaries][static-binaries]]

** privesc/unix/

- [[https://github.com/stealthcopter/deepce][deepce]]
- [[https://github.com/The-Z-Labs/linux-exploit-suggester][les]]
- [[https://github.com/peass-ng/PEASS-ng][linpeas]]
- [[https://github.com/diego-treitos/linux-smart-enumeration][lse]]
- [[https://github.com/DominicBreuker/pspy][pspy]]
- [[https://github.com/luijait/PwnKit-Exploit][pwnkit]]

** privesc/win/

- [[https://github.com/EmpireProject/Empire][empire]]
- [[https://github.com/r3motecontrol/Ghostpack-CompiledBinaries][ghostpack-compiled]]
- [[https://github.com/Kevin-Robertson/Inveigh][inveigh]]
- [[https://github.com/AlessandroZ/LaZagne][lazagne]]
- [[https://github.com/gentilkiwi/mimikatz][mimikatz]]
- [[https://github.com/PowerShellMafia/PowerSploit][powersploit]]
- [[https://github.com/itm4n/PrintSpoofer][printspoofer]]
- [[https://github.com/itm4n/PrivescCheck][privesccheck]]
- [[https://github.com/ghostpack/Rubeus][rubeus]]
- [[https://github.com/SpecterOps/SharpHound][sharphound]]
- [[https://github.com/rasta-mouse/Watson][watson]]
- [[https://github.com/bitsadmin/wesng][wes]]
- [[https://github.com/peass-ng/PEASS-ng][winpeas]]
